import React, { useState } from 'react';
import { repositoryApi } from '../services/api';

interface GitHubPRModalProps {
  isOpen: boolean;
  onClose: () => void;
  defaultRepoUrl?: string;
  testName: string;
  filePath: string;
  unifiedDiff?: string;
  newContent?: string;
}

export default function GitHubPRModal({
  isOpen,
  onClose,
  defaultRepoUrl = '',
  testName,
  filePath,
  unifiedDiff,
  newContent
}: GitHubPRModalProps) {
  const [repoUrl, setRepoUrl] = useState(defaultRepoUrl || 'https://github.com/aditya-padmar/FlakeGuard');
  const [token, setToken] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [title, setTitle] = useState(`fix(flakeguard): remediate ${testName}`);
  const [body, setBody] = useState(
    `### FlakeGuard Automated Remediation PR\n\n` +
    `This PR applies an automated fix generated by FlakeGuard for the flaky test **\`${testName}\`** in \`${filePath}\`.\n\n` +
    `#### Code Changes\n\`\`\`diff\n${unifiedDiff || '# Automated patch'}\n\`\`\`\n\n` +
    `Generated by **FlakeGuard AI Agent (IBM Bob 2.0)**.`
  );
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [prResult, setPrResult] = useState<{ pr_url: string; pr_number: number } | null>(null);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token.trim()) {
      setError('Please provide a GitHub Personal Access Token with repo/content write permissions.');
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const res = await repositoryApi.createPR({
        repo_url: repoUrl.trim(),
        token: token.trim(),
        file_path: filePath,
        new_content: newContent || '# Patched content',
        title,
        body,
        base_branch: baseBranch
      });
      setPrResult(res.data);
    } catch (err: any) {
      const msg = err.response?.data?.detail || err.message || 'Failed to open Pull Request';
      setError(`GitHub API Error: ${msg}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="modal-overlay" style={{
      position: 'fixed',
      top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(15, 23, 42, 0.65)',
      backdropFilter: 'blur(4px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '1rem'
    }}>
      <div className="modal-content" style={{
        background: '#ffffff',
        borderRadius: '12px',
        maxWidth: '560px',
        width: '100%',
        boxShadow: '0 20px 25px -5px rgba(0,0,0,0.2)',
        overflow: 'hidden'
      }}>
        <div style={{
          padding: '1.25rem 1.5rem',
          background: 'linear-gradient(135deg, #1e293b, #0f172a)',
          color: '#ffffff',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <div>
            <h3 style={{ margin: 0, fontSize: '1.15rem' }}>🐙 Create GitHub Pull Request</h3>
            <p style={{ margin: '0.2rem 0 0', fontSize: '0.8rem', color: '#94a3b8' }}>
              Publish remediation diff directly to GitHub
            </p>
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'transparent',
              border: 'none',
              color: '#ffffff',
              fontSize: '1.2rem',
              cursor: 'pointer'
            }}
          >
            ✕
          </button>
        </div>

        <div style={{ padding: '1.5rem' }}>
          {prResult ? (
            <div style={{ textAlign: 'center', padding: '1rem 0' }}>
              <span style={{ fontSize: '3rem' }}>🎉</span>
              <h4 style={{ margin: '0.75rem 0 0.25rem', color: '#0f172a' }}>Pull Request Created!</h4>
              <p style={{ fontSize: '0.9rem', color: '#64748b' }}>
                Pull Request <strong>#{prResult.pr_number}</strong> was successfully opened.
              </p>
              <div style={{ marginTop: '1.25rem', display: 'flex', gap: '0.75rem', justifyContent: 'center' }}>
                <a
                  href={prResult.pr_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn-primary"
                  style={{ textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}
                >
                  View on GitHub ↗
                </a>
                <button className="btn-secondary" onClick={onClose}>
                  Done
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '0.25rem' }}>
                  Target Repository URL
                </label>
                <input
                  type="text"
                  value={repoUrl}
                  onChange={(e) => setRepoUrl(e.target.value)}
                  required
                  style={{ width: '100%', boxSizing: 'border-box' }}
                />
              </div>

              <div>
                <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '0.25rem' }}>
                  GitHub Personal Access Token (PAT)
                </label>
                <input
                  type="password"
                  placeholder="ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                  value={token}
                  onChange={(e) => setToken(e.target.value)}
                  required
                  style={{ width: '100%', boxSizing: 'border-box' }}
                />
                <span style={{ fontSize: '0.75rem', color: '#64748b' }}>
                  Requires write access to repo contents and pull requests.
                </span>
              </div>

              <div style={{ display: 'flex', gap: '1rem' }}>
                <div style={{ flex: 2 }}>
                  <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '0.25rem' }}>
                    PR Title
                  </label>
                  <input
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    required
                    style={{ width: '100%', boxSizing: 'border-box' }}
                  />
                </div>
                <div style={{ flex: 1 }}>
                  <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '0.25rem' }}>
                    Base Branch
                  </label>
                  <input
                    type="text"
                    value={baseBranch}
                    onChange={(e) => setBaseBranch(e.target.value)}
                    style={{ width: '100%', boxSizing: 'border-box' }}
                  />
                </div>
              </div>

              <div>
                <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#334155', display: 'block', marginBottom: '0.25rem' }}>
                  PR Description
                </label>
                <textarea
                  rows={4}
                  value={body}
                  onChange={(e) => setBody(e.target.value)}
                  style={{
                    width: '100%',
                    boxSizing: 'border-box',
                    padding: '0.5rem',
                    borderRadius: '6px',
                    border: '1px solid #cbd5e1',
                    fontSize: '0.85rem',
                    fontFamily: 'monospace'
                  }}
                />
              </div>

              {error && (
                <div style={{
                  padding: '0.75rem',
                  background: '#fef2f2',
                  border: '1px solid #fecaca',
                  borderRadius: '6px',
                  color: '#991b1b',
                  fontSize: '0.85rem'
                }}>
                  {error}
                </div>
              )}

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '0.5rem' }}>
                <button type="button" className="btn-secondary" onClick={onClose} disabled={loading}>
                  Cancel
                </button>
                <button type="submit" className="btn-primary" disabled={loading} style={{ minWidth: '130px' }}>
                  {loading ? 'Opening PR...' : '🚀 Submit Pull Request'}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
